- name: Configure Nginx
  hosts: web1
  become: yes
  vars:
    email: "{{ lookup('env','CERTBOT_EMAIL') }}"
    domain_name: "{{ lookup('env','DOMAIN_NAME') }}"
    server_build_path: "/var/www/{{ domain_name }}"
    nginx_sites_available: "/etc/nginx/sites-available"
    nginx_sites_enabled: "/etc/nginx/sites-enabled"

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Install Certbot
      apt:
        name: [certbot, python3-certbot-nginx]
        state: present
        update_cache: yes

    - name: Check if SSL certificate exists
      stat:
        path: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
      register: ssl_cert_before_certbot_exitsts

    - name: Create Nginx HTTP config
      template:
        src: nginx.conf.j2
        dest: "{{ nginx_sites_available }}/{{ domain_name }}-http"
      vars:
        ssl_exists: "{{ ssl_cert_before_certbot_exitsts.stat.exists }}"

    - name: Create symlink for HTTP config
      file:
        src: "{{ nginx_sites_available }}/{{ domain_name }}-http"
        dest: "{{ nginx_sites_enabled }}/{{ domain_name }}-http"
        state: link
      notify: Restart Nginx

    - name: Obtain SSL certificate
      command: >
        certbot certonly --webroot -w {{ server_build_path }} -n --agree-tos --email {{ email }} -d {{ domain_name }}
      when:
        - not ssl_cert_before_certbot_exitsts.stat.exists

    - name: Check if SSL certificate exists
      stat:
        path: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
      register: ssl_cert_after_certbot_exitsts

    - name: Create Nginx HTTPS config
      template:
        src: nginx.conf.https.j2
        dest: "{{ nginx_sites_available }}/{{ domain_name }}"

    - name: Create symlink for HTTPS config
      file:
        src: "{{ nginx_sites_available }}/{{ domain_name }}"
        dest: "{{ nginx_sites_enabled }}/{{ domain_name }}"
        state: link
      notify: Restart Nginx

    - name: Update Nginx HTTP config after certbot
      template:
        src: nginx.conf.j2
        dest: "{{ nginx_sites_available }}/{{ domain_name }}-http"
      vars:
        ssl_exists: "{{ ssl_cert_after_certbot_exitsts.stat.exists }}"
      when:
        - not ssl_cert_before_certbot_exitsts.stat.exists
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
